linters:
  enable:
    - megacheck
    - govet
    - gofumpt

  disable:
    - maligned
    - prealloc
  presets:
    - bugs
    - unused
  fast: false

linters-settings:
  gofumpt:
    module-path: hertz
    extra-rules: true

run:
  concurrency: 5