linters:
  enable:
    - megacheck
    - govet
    - gofumpt
    - nilnil
  disable:
    - maligned
    - prealloc
    - errchkjson
  presets:
    - bugs
    - unused
  fast: false

linters-settings:
  gofumpt:
    module-path: hertz
    extra-rules: true
  staticcheck:
    checks: [
      "all",
      "-SA5008"
    ]

run:
  concurrency: 5