name: Run golangci-lint
on:
  push:
    branches:
      - main
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: golang-ci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: v1.56.2
